// ============================================================
//  SpoolmanScale – Localization (i18n)
//  lang.h — String IDs, enum, T() macro
//  Languages: DE (0) | EN (1)
// ============================================================
#pragma once
#include <stdint.h>

enum Lang { LANG_DE = 0, LANG_EN = 1 };
extern Lang g_lang;

// Date format: 0 = DD.MM.YYYY  |  1 = YYYY-MM-DD
extern uint8_t g_date_fmt;

enum StringID {
  // Navigation
  STR_CANCEL,
  STR_BACK,
  STR_SAVE,
  STR_CONFIRM,
  STR_CLOSE,
  STR_RETRY,
  STR_FORCE_LINK,
  STR_ENTER_NEW_ID,

  // Mainscreen Labels
  STR_LBL_UID,
  STR_LBL_UUID,
  STR_LBL_MATERIAL,
  STR_LBL_SPOOLMAN,
  STR_LBL_SCALE,
  STR_LBL_LAST_USED,
  STR_LBL_LAST_DRIED,
  STR_LBL_TEMP,
  STR_LBL_VENDOR,
  STR_LBL_ARTICLE,
  STR_LBL_PRODUCTION,
  STR_LBL_SPOOLMAN_ID,

  // Mainscreen Status
  STR_WAIT_SCAN,
  STR_TAG_FOUND,
  STR_NO_WIFI,
  STR_WAIT,
  STR_WAIT_SCAN_SM,
  STR_UNKNOWN,
  STR_NOT_READABLE,
  STR_TODAY,
  STR_YESTERDAY,
  STR_DAYS_AGO,
  STR_ERR_SAVE,
  STR_NOT_IN_SPOOLMAN,
  STR_ARCHIVED,
  STR_READING_TAG,

  // Mainscreen Buttons
  STR_BTN_WEIGHT,
  STR_BTN_DRIED,
  STR_BTN_LINK,

  // Welcome Screen
  STR_WELCOME_SUB,
  STR_WELCOME_HINT,
  STR_BTN_SETUP_NOW,

  // WiFi Setup
  STR_WIFI_TITLE,
  STR_WIFI_SCAN,
  STR_WIFI_SELECT,
  STR_WIFI_RESCAN,
  STR_WIFI_NO_NET,
  STR_WIFI_PASS_TITLE,
  STR_WIFI_PASS_HINT,
  STR_WIFI_CONNECTING,
  STR_WIFI_SUCCESS,
  STR_WIFI_FAIL,
  STR_BTN_CONNECT,

  // Spoolman IP
  STR_SPOOLMAN_TITLE,
  STR_SPOOLMAN_HINT,

  // Settings
  STR_SETTINGS_TITLE,
  STR_TILE_CONNECTION,
  STR_TILE_CONN_SUB,
  STR_TILE_SCALE,
  STR_TILE_SCALE_SUB,
  STR_TILE_DISPLAY,
  STR_TILE_DISPLAY_SUB,
  STR_TILE_SYSTEM,
  STR_TILE_SYSTEM_SUB,
  STR_BTN_TARE,

  // Connection
  STR_CONN_TITLE,
  STR_BTN_WIFI_SETTINGS,
  STR_BTN_WIFI_NONE,
  STR_BTN_SPOOLMAN,

  // Scale
  STR_SCALE_TITLE,
  STR_BTN_CALIBRATE,
  STR_BTN_CAL_SUB,
  STR_BTN_BAGWEIGHT,
  STR_BTN_BAG_SUB,
  STR_BTN_BAG_UI,

  // Calibration
  STR_CAL_TITLE,
  STR_CAL_DESC,
  STR_CAL_FACTOR,
  STR_CAL_OK,
  STR_CAL_SCALE_NOT_READY,
  STR_CAL_ZERO_ERR,
  STR_BTN_CALCULATE,

  // Bag weight
  STR_BAG_TITLE,
  STR_BAG_DESC,
  STR_BAG_SAVED,
  STR_BAG_INVALID,

  // Display
  STR_DISPLAY_TITLE,
  STR_BRIGHT_LABEL,
  STR_DIM_LABEL,
  STR_SLEEP_LABEL,
  STR_DISPLAY_HINT,

  // System
  STR_SYSTEM_TITLE,
  STR_BTN_LANGUAGE,
  STR_BTN_LANG_SUB,
  STR_BTN_FW_UPDATE,
  STR_BTN_FW_SUB,
  STR_BTN_INFO,
  STR_BTN_INFO_SUB,

  // Language screen
  STR_LANG_TITLE,
  STR_LANG_HINT,
  STR_LANG_EN_SUB,
  STR_DATE_FMT_LABEL,

  // OTA
  STR_OTA_TITLE,
  STR_OTA_BROWSER,
  STR_OTA_BROWSER_SUB,
  STR_OTA_GITHUB,
  STR_OTA_GITHUB_SUB,
  STR_OTA_BROWSER_TITLE,
  STR_OTA_NO_WIFI,
  STR_OTA_OPEN_BROWSER,
  STR_OTA_FILE_HINT,
  STR_OTA_WAITING,
  STR_OTA_UPLOADING,
  STR_OTA_SUCCESS,
  STR_OTA_FAIL,
  STR_BTN_STOP_SERVER,
  STR_OTA_CURRENT,

  // Info Screen
  STR_INFO_TITLE,
  STR_INFO_VERSION,
  STR_INFO_HINT,

  // QR Popups
  STR_QR_KOFI_DESC,
  STR_QR_GITHUB_DESC,
  STR_QR_DISCORD_DESC,
  STR_QR_MAKER_DESC,

  // Weight popup
  STR_POPUP_DRIED_Q,
  STR_POPUP_WEIGHT_Q,
  STR_BTN_NO_BAG,
  STR_BTN_WITH_BAG,
  STR_BTN_NEW_SPOOL,
  STR_BTN_EMPTY_SPOOL,
  STR_BTN_ARCHIVE,
  STR_BTN_CONFIRMED,

  // Spool weight sub-popup
  STR_SPOOL_WEIGHT_TITLE,
  STR_BTN_THIS_SPOOL,
  STR_BTN_THIS_FILAMENT,
  STR_BTN_THIS_VENDOR,

  // Link Flow
  STR_LINK_BAMBU_TITLE,
  STR_LINK_NTAG_TITLE,
  STR_LINK_NOT_IN_SM,
  STR_BTN_ENTER_ID,
  STR_BTN_FROM_LIST,
  STR_LINK_ID_TITLE,
  STR_LINK_CHECKING,
  STR_LINK_ID_NOT_FOUND,
  STR_LINK_HTTP_ERR,
  STR_LINK_JSON_ERR,
  STR_LINK_NO_WIFI,
  STR_WARN_A_TITLE,
  STR_WARN_A_INFO,
  STR_BTN_OVERWRITE,
  STR_WARN_B_TITLE,
  STR_WARN_B_DETAILS,
  STR_VENDOR_TITLE,
  STR_MAT_TITLE,
  STR_SPOOLS_TITLE,
  STR_NO_VENDORS,
  STR_NO_MATERIALS,
  STR_NO_SPOOLS,
  STR_CONFIRM_LINK,
  STR_LINK_OK,
  STR_LINK_FAIL,

  // Tare
  STR_TARE_TITLE,
  STR_TARE_DESC,
  STR_TARE_OK,
  STR_TARE_NOT_READY,

  STR_API_ERROR,

  // Reboot popup
  STR_REBOOT_TITLE,
  STR_REBOOT_MSG,
  STR_REBOOT_BTN,

  // WiFi connecting result
  STR_WIFI_CONNECTED_IP,
  STR_WIFI_CONN_FAILED,

  // WiFi quality
  STR_WIFI_QUAL_EXCELLENT,
  STR_WIFI_QUAL_GOOD,
  STR_WIFI_QUAL_MEDIUM,
  STR_WIFI_QUAL_WEAK,
  STR_WIFI_STATUS_CONNECTED,
  STR_WIFI_STATUS_DISCONNECTED,

  // Numpad buttons
  STR_BTN_SAVE,

  // Spool list title
  STR_SPOOLS_BAMBU,
  STR_SPOOLS_ALL,

  // Settings calibration sub
  STR_CAL_FACTOR_SHORT,

  // Archive confirm
  STR_ARCHIVE_CONFIRM,

  // Weight popup archive button
  STR_BTN_ARCHIVE_EMPTY,

  // Welcome language select
  STR_WELCOME_LANG_TITLE,
  STR_WELCOME_LANG_HINT,

  // WiFi scan count
  STR_WIFI_NETWORKS_FOUND,

  // Bag weight current label
  STR_BAG_CURRENT,

  // Warn popup A fields
  STR_WARN_A_SPOOL_INFO,
  STR_WARN_A_SPOOL_SHORT,

  // Link entry context
  STR_LINK_CTX_NOT_IN_SM,

  // Weight popup buttons (with snprintf)
  STR_BTN_NO_BAG_VAL,
  STR_BTN_WITH_BAG_VAL,
  STR_BTN_NEW_SPOOL_VAL,
  STR_BTN_TARE_ZERO,

  // First boot welcome screen
  STR_FIRSTBOOT_TITLE,
  STR_FIRSTBOOT_SUB,
  STR_FIRSTBOOT_HINT,
  STR_FIRSTBOOT_BTN,

  // Extra fields screen
  STR_EXTRA_FIELDS_TITLE,
  STR_EXTRA_FIELDS_CHECK_BTN,
  STR_EXTRA_FIELDS_CHECKING,
  STR_EXTRA_FIELDS_ALL_OK,
  STR_EXTRA_FIELDS_MISSING,
  STR_EXTRA_FIELDS_CREATE_BTN,
  STR_EXTRA_FIELDS_CONFIRM_TITLE,
  STR_EXTRA_FIELDS_CONFIRM_MSG,
  STR_EXTRA_FIELDS_CREATING,
  STR_EXTRA_FIELDS_CREATED_OK,
  STR_EXTRA_FIELDS_CREATE_FAIL,
  STR_EXTRA_FIELDS_NO_WIFI,
  STR_EXTRA_FIELDS_NO_SPOOLMAN,
  STR_EXTRA_FIELDS_SKIP,
  STR_EXTRA_FIELDS_HINT,

  // Calibration reminder screen (end of first setup)
  STR_CAL_REMINDER_TITLE,
  STR_CAL_REMINDER_MSG,
  STR_CAL_REMINDER_LATER,
  STR_CAL_REMINDER_NOW,

  // Calibration TARE hint
  STR_CAL_TARE_HINT,

  // Extra fields test button
  STR_EF_TEST_BTN,
  STR_EF_TEST_CREATED,
  STR_EF_TEST_EXISTS,
  STR_EF_TEST_FAIL,

  // Spoolman IP validation
  STR_SPOOLMAN_TESTING,
  STR_SPOOLMAN_OK,
  STR_SPOOLMAN_FAIL,
  STR_SPOOLMAN_RETRY,
  STR_SPOOLMAN_SKIP,

  // More info filament screen
  STR_BTN_MORE_INFO,

  // GitHub OTA check screen
  STR_GH_OTA_TITLE,
  STR_GH_OTA_CHECK_BTN,
  STR_GH_OTA_CHECKING,
  STR_GH_OTA_NO_WIFI,
  STR_GH_OTA_UP_TO_DATE,
  STR_GH_OTA_UPDATE_AVAIL,
  STR_GH_OTA_UPDATE_BTN,
  STR_GH_OTA_FLASHING,
  STR_GH_OTA_FLASH_OK,
  STR_GH_OTA_FLASH_FAIL,
  STR_GH_OTA_INSTALLED,
  STR_GH_OTA_LATEST,
  STR_GH_OTA_PRERELEASE,

  // Last Used Mode screen
  STR_BTN_LASTUSED_MODE,
  STR_BTN_LASTUSED_MODE_SUB,
  STR_LASTUSED_TITLE,
  STR_LASTUSED_OPT_OSM,
  STR_LASTUSED_OPT_WEIGHED,
  STR_LASTUSED_DESC_OSM,
  STR_LASTUSED_DESC_WEIGHED,

  // Factory Reset
  STR_BTN_FACTORY_RESET,
  STR_BTN_FACTORY_RESET_SUB,
  STR_FACTORY_RESET_TITLE,
  STR_FACTORY_RESET_MSG,
  STR_FACTORY_RESET_CONFIRM,

  // Copy spool flow
  STR_BTN_COPY_SPOOL,
  STR_COPY_TITLE,
  STR_COPY_ID_BTN,
  STR_COPY_ACTIVE_BTN,
  STR_COPY_ARCHIVED_BTN,
  STR_COPY_CONFIRM_TITLE,
  STR_COPY_CONFIRM_MSG,
  STR_COPY_OK,
  STR_COPY_FAIL,
  STR_COPY_NO_SPOOLS,
  STR_COPY_LIMIT_HIT,

  // First boot skip button
  STR_BTN_SKIP_SETUP,

  // Unlink spool
  STR_UNLINK_BTN,
  STR_UNLINK_TITLE,
  STR_UNLINK_MSG,
  STR_UNLINK_CONFIRM,

  // Scale boot status
  STR_SCALE_CALIBRATING,
  STR_WIFI_CONNECTING_BOOT,
  STR_BOOTING,

  // Reboot button in system screen
  STR_BTN_REBOOT,
  STR_BTN_REBOOT_SUB,

  // Whole gram toggle
  STR_WHOLE_GRAM,

  // List limit info items
  STR_LIST_MORE_SPOOLS,
  STR_LIST_MORE_VENDORS,
  STR_LIST_MORE_MATS,

  // Auto-Weight
  STR_AUTO_WEIGHT_TITLE,
  STR_AUTO_WEIGHT_INFO,
  STR_AUTO_WEIGHT_ENABLE,
  STR_AUTO_WEIGHT_DISABLE,

  // Location
  STR_BTN_LOCATION,
  STR_LOCATION_TITLE,
  STR_LOCATION_NONE,
  STR_LOCATION_LOADING,
  STR_LOCATION_NO_WIFI,
  STR_LOCATION_SAVED,
  STR_LOCATION_FAIL,
  STR_LOCATION_NO_LOCATIONS,
  STR_LOCATION_HINT_EMPTY,
  STR_LOCATION_LIMIT_HIT,

  // No spools hint (link flow)
  STR_NO_SPOOLS_HINT,

  // Auto location popup toggle
  STR_BTN_AUTO_LOC_POPUP,
  STR_BTN_AUTO_LOC_POPUP_SUB,
  STR_AUTO_LOC_POPUP_TITLE,
  STR_AUTO_LOC_POPUP_MSG,

  // Drying reminder
  STR_BTN_DRYING_REMINDER,
  STR_BTN_DRYING_REMINDER_SUB,
  STR_DRYING_REMINDER_TITLE,
  STR_DRYING_REMINDER_COMING_SOON,

  // Drying Reminder Screen
  STR_DRY_MODE_OFF,
  STR_DRY_MODE_MATERIAL,
  STR_DRY_MODE_MANUAL,
  STR_DRY_OFF_DESC,
  STR_DRY_MAT_HINT,
  STR_DRY_MAT_HDR_MAT,
  STR_DRY_MAT_HDR_YELLOW,
  STR_DRY_MAT_HDR_RED,
  STR_DRY_MAT_HDR_MULT,
  STR_DRY_MAT_FOOTNOTE,
  STR_DRY_MAN_YELLOW_LBL,
  STR_DRY_MAN_RED_LBL,
  STR_DRY_MAN_EDIT_HINT,
  STR_DRY_MAN_INFO,
  STR_DRY_DAYS_UNIT,
  STR_DRY_NUMPAD_YELLOW_TITLE,
  STR_DRY_NUMPAD_RED_TITLE,
  STR_DRY_MAT_EFF_NOTE,
  STR_DRY_SEALED_HDR,

  STR_COUNT
};

extern const char* const STRINGS[STR_COUNT][2];

// Macro: T(STR_XXX) -> returns the string in the current language
#define T(id) STRINGS[id][g_lang]
